name: Recycle My Boat
favicon: null
layout_spectrum: 0.6444739727303386
typography_spectrum: 0.046810252126306295
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.9579920298419893
  lightness: 0.34349360573105514
  saturation: 0.3990846478845924
  rhythmicContrast: 0.4774971678853035
purpose: []
